name: uvc-ctrl

on:
  push:
    paths:
      - ./*.cpp
      - .github/workflows/build.yml

permissions:
  contents: write

# env:
# CMAKE_CXX_COMPILER_LAUNCHER: ccache

jobs:
  uvc-ctrl_matrix:
    strategy:
      matrix:
        include:
          - { platform: vs, os: windows-latest, toolchain: vs-stable }
          # - {
          #     platform: msys2,
          #     os: ubuntu-latest,
          #     prefix: mingw-w64,
          #     toolchain: x86_64-w64-mingw32-gcc,
          #   }
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash
        # working-directory: ${{ github.workflow }}

    steps:
      - uses: actions/checkout@v5

      # - name: MSYS2 Apt Cross Compile
      #   if: matrix.platform == 'msys2' && runner.os == 'Linux'
      #   run: |
      #     sudo apt install gcc-${{ matrix.prefix }} g++-${{ matrix.prefix }} binutils-${{ matrix.prefix }}

      - name: Install Chalet
        uses: jaxxstorm/action-install-gh-release@v2.1.0
        with:
          repo: chalet-org/chalet
          cache: enable
          extension: .zip
          prerelease: "false"

      - name: Chalet Test / Version
        run: |
          chalet --version

      - name: Chalet Configure
        run: chalet configure --toolchain ${{ matrix.toolchain }}

      - name: Chalet Bundle
        if: matrix.platform != 'ios'
        run: |
          chalet bundle --compiler-cache --show-commands

      - name: iOS Bundle
        if: matrix.platform == 'ios'
        run: |
          ./${{ github.workflow }}.sh

      - name: LS check built lib
        if: matrix.platform != 'ios'
        run: |
          unzip dist/*.zip
          ls -alfR dist

      - name: Rename and Publish Release
        env:
          GITHUB_TOKEN: ${{ github.TOKEN }}
        run: |
          mv dist/${{ github.workflow }}.zip oflib_${{ github.workflow }}_${{ matrix.platform }}.zip
          ls -alF *.zip
          gh release upload v0.12.1 *.zip --clobber
